apiVersion: apps/v1
kind: Deployment
metadata:
  name: booking-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: booking
  template:
    metadata:
      labels:
        app: booking
    spec:
      containers:
        - name: booking
          image: frankjia/noqclinic-booking
          env:
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NATS_URL
              value: "http://nats-srv:4222"
            - name: NATS_CLUSTER_ID
              value: noqclinic
            - name: MONGO_URI
              value: "mongodb://booking-mongo-srv:27017/booking"
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY
---
apiVersion: v1
kind: Service
metadata:
  name: booking-srv
spec:
  selector:
    app: booking
  ports:
    - name: booking
      protocol: TCP
      port: 3000
      targetPort: 3000