apiVersion: apps/v1
kind: Deployment
metadata:
  name: pre-diagnosis-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pre-diagnosis
  template:
    metadata:
      labels:
        app: pre-diagnosis
    spec:
      containers:
        - name: pre-diagnosis
          image: frankjia/noqclinic-pre-diagnosis
          env:
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NATS_URL
              value: "http://nats-srv:4222"
            - name: NATS_CLUSTER_ID
              value: noqclinic
            - name: MONGO_URI
              value: "mongodb://pre-diagnosis-mongo-srv:27017/pre-diagnosis"
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY
---
apiVersion: v1
kind: Service
metadata:
  name: pre-diagnosis-srv
spec:
  selector:
    app: pre-diagnosis
  ports:
    - name: pre-diagnosis
      protocol: TCP
      port: 3000
      targetPort: 3000